# Site settings
name: Blog  of  JamesPxy
email: 1280272327@qq.com
author: JamesPxy
url: https://lebronjamespxy.github.io/jekyll_demo/
resume_site: https://lebronjamespxy.github.io/jekyll_demo/
github: https://github.com/LebronJamesPXY
baseurl: ""
description: Action  speaks louder than  words , Just do  it !
meta_description: 彭湃的个人博客;坚持积累说到做到
motto: Action  speaks louder than  words , Just do  it !
banner: 生命不息，奋斗不止！

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: luoyan35714
highlighter: rouge

# Build settings
markdown: kramdown

FB:
  comments :
    provider : duoshuo
    duoshuo:
        short_name : luoyan35714
    disqus :
        short_name : freudkang
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light